###服务端口号
server:
  port: 8100
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: localhost
  client:
    serviceUrl:  # 其他服务向Eureka服务器注册
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 如果是多个Eurek服务之间的服务，就需要用,分开
    ###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: false
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: false
